const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const c=require('../lib/cms-oauth.cjs');const auth=require('../api/cms/auth');const callback=require('../api/cms/callback');const {renderPost,validate}=require('../scripts/build-site.cjs');
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.body=v;}};}
process.env.CMS_GITHUB_CLIENT_ID='test-client';process.env.CMS_GITHUB_CLIENT_SECRET='test-secret';process.env.CMS_STATE_SECRET='test-state-key-32-characters-minimum';
test('signed state rejects tampering and expiration',()=>{const value=c.seal({at:Date.now(),state:'test'},process.env.CMS_STATE_SECRET);assert.equal(c.unseal(value,process.env.CMS_STATE_SECRET).state,'test');assert.throws(()=>c.unseal(value+'x',process.env.CMS_STATE_SECRET));assert.throws(()=>c.unseal(c.seal({at:Date.now()-601000},process.env.CMS_STATE_SECRET),process.env.CMS_STATE_SECRET));});
test('authorization uses fixed callback, PKCE and no broad OAuth scope',()=>{const r=response();auth({method:'GET',query:{provider:'github'}},r);assert.equal(r.statusCode,302);const u=new URL(r.headers.Location);assert.equal(u.searchParams.get('redirect_uri'),c.CALLBACK);assert.equal(u.searchParams.get('scope'),null);assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.match(r.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Lax/);});
test('callback rejects state before network and restricts popup destination',async()=>{const r=response();await callback({method:'GET',headers:{},query:{code:'invalid',state:'invalid'}},r);assert.equal(r.statusCode,400);assert.match(r.headers['Content-Security-Policy'],/frame-ancestors 'none'/);assert.match(r.body,/event.origin!==origin/);assert.doesNotMatch(r.body,/postMessage\([^)]*['"]\*['"]/);});
test('callback checks user and repository before releasing token',async()=>{const original=global.fetch;try{let calls=0;global.fetch=async()=>({ok:true,json:async()=>[ {access_token:'fake-token'}, {login:'wrong-user'}, {permissions:{push:true}} ][calls++]});const value=c.seal({at:Date.now(),state:'state',verifier:'verifier'},process.env.CMS_STATE_SECRET);const r=response();await callback({method:'GET',headers:{cookie:c.COOKIE+'='+value},query:{state:'state',code:'code'}},r);assert.equal(r.statusCode,400);assert.doesNotMatch(r.body,/fake-token/);}finally{global.fetch=original;}});
test('existing published articles and funnel are preserved exactly',()=>{for(const file of fs.readdirSync('content/blog')){const slug=file.slice(0,-5);assert.equal(fs.readFileSync(`dist/blog-${slug}.html`,'utf8'),fs.readFileSync(`blog-${slug}.html`,'utf8'));}assert.equal(fs.readFileSync('dist/outbound-assessment.html','utf8'),fs.readFileSync('outbound-assessment.html','utf8'));assert.equal(fs.readFileSync('dist/index.html','utf8'),fs.readFileSync('index.html','utf8'));});
test('new articles escape metadata and sanitize executable markup',()=>{const p={title:'<script>bad()</script>',date:'2026-09-24',author:'BPO Hive',category:'Guides',description:'Test',body:'## Hello\n\n<script>alert(1)</script>\n\n<img src="x" onerror="bad()">\n\n[bad](javascript:alert(1))'};validate(p,'new-guide');const html=renderPost(p,'new-guide');const $=require('cheerio').load(html);assert.equal($('h1 script,article script,[onerror],a[href^="javascript:"]').length,0);assert.equal($('h1').text(),p.title);assert.match(html,/id="hello"/);assert.match(html,/https:\/\/www.bpohive.com\/blog-new-guide/);assert.throws(()=>validate({...p,featured_image:'/assets/../secret.png'},'new-guide'));assert.throws(()=>validate(p,'../index'));});
