const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),c=require('cheerio');
const handler=require('../api/growth-lead');const {regions,services,industries}=require('../scripts/growth-content.cjs');
const assessmentHandler=require('../api/outbound-assessment');
const load=p=>c.load(fs.readFileSync('dist/'+p+'.html','utf8'));
test('regional and editorial pages meet length, visible FAQ and schema requirements',()=>{
 for(const [slug,min,max] of [...regions.map(r=>[r.slug,1000,Infinity]),...services.map(s=>['services/'+s[0],900,1200]),...industries.map(s=>['industries/'+s[0],900,1200])]){const $=load(slug),words=$('.growth .content').text().split(/\s+/).filter(Boolean).length;assert.ok(words>=min&&words<=max,`${slug}: ${words} words`);assert.equal($('h1').length,1);const nodes=$('script[type="application/ld+json"]').map((i,e)=>JSON.parse($(e).html())).get().flatMap(x=>x['@graph']||[x]);assert.ok(nodes.some(x=>x['@type']==='Service'&&x.areaServed.length));const faq=nodes.find(x=>x['@type']==='FAQPage');assert.equal(faq.mainEntity.length,$('main details').length);for(const q of faq.mainEntity)assert.ok($('main').text().includes(q.acceptedAnswer.text));}
});
test('original assessment gates the calendar at $4,000 without a new layout',async()=>{
 const $=load('outbound-assessment');assert.equal($('#growth-form,#quick-path,#full-assessment').length,0);assert.equal($('#assessment-form').length,1);assert.equal($('#budget option[value="4000_4999"]').text(),'$4,000–$4,999');assert.equal($('#budget option[value="under_4000"]').length,1);
 const old=global.fetch,hook=process.env.ZAPIER_WEBHOOK_URL;process.env.ZAPIER_WEBHOOK_URL='https://example.invalid/test';let event;global.fetch=async(url,args)=>{event=JSON.parse(args.body);return {ok:true};};
 try{for(const budget of ['under_4000','4000_4999','5000_9999','10000_plus']){const r=res();await assessmentHandler({method:'POST',headers:{'x-forwarded-for':'assessment-'+ip++},body:{firstName:'Test',lastName:'Buyer',email:'buyer@example.com',phone:'+15026773800',jobTitle:'CEO',companyName:'Test Company',website:'https://example.com',offer:'Software',targetMarket:'Canada',averageSale:'$5,000–$9,999',service:'Appointment setting',budget,timeline:'This month'}},r);assert.equal(r.code,200);assert.equal(r.body.qualified,budget!=='under_4000');assert.equal(Boolean(r.body.bookingUrl),budget!=='under_4000');assert.equal(r.body.forecast.meetingRange,'15–22');if(budget==='under_4000')assert.equal(event.prefilled_calendly_link,'');else assert.match(event.prospect_email_html,/Starting investment: \$4,000/);}}
 finally{global.fetch=old;if(hook===undefined)delete process.env.ZAPIER_WEBHOOK_URL;else process.env.ZAPIER_WEBHOOK_URL=hook;}
});
test('all internal navigation/footer URLs resolve to built files, careers is isolated',()=>{
 const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()&&!['assets','admin'].includes(x.name)?walk(path.join(d,x.name)):x.isFile()&&x.name.endsWith('.html')?[path.join(d,x.name)]:[]);
 for(const f of walk('dist')){const $=c.load(fs.readFileSync(f));$('nav a[href],footer a[href]').each((i,e)=>{const h=$(e).attr('href');if(/^(?:[a-z]+:|#|\/\/)/i.test(h))return;const u=new URL(h,'https://www.bpohive.com/'+f.slice(5));let p='dist'+u.pathname;if(p==='dist/')p+='index.html';assert.ok(fs.existsSync(p)||fs.existsSync(p+'.html'),`${f}: ${h}`);});}
 const $=load('careers');assert.match($('meta[name=robots]').attr('content'),/noindex/);assert.equal($('a[href*="outbound-assessment"],a[href*="wa.me"],a[href^="tel:"]').length,0);assert.equal($('.growth-apply').attr('href'),'#open-positions');assert.match(load('form-received')('meta[name=robots]').attr('content'),/noindex/);
});
function res(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(b){this.body=b;return this;}};}let ip=1;
async function submit(b){const r=res();await handler({method:'POST',headers:{'x-forwarded-for':'test-'+ip++},body:b},r);return r;}
test('server validates qualification and preserves notification contract without inventing forecasts',async()=>{
 const old=global.fetch,hook=process.env.ZAPIER_WEBHOOK_URL;process.env.ZAPIER_WEBHOOK_URL='https://example.invalid/test';let events=[];global.fetch=async(url,args)=>{events.push(JSON.parse(args.body));return {ok:true};};
 try{const b={type:'strategy',name:'Test Buyer',email:'buyer@example.com',website:'example.com',targetMarket:'Canada'};for(const budget of ['under_4000','not_sure','4000_6999','7000_9999','10000_plus']){const r=await submit({...b,budget});assert.equal(r.code,200);assert.equal(r.body.qualified,['4000_6999','7000_9999','10000_plus'].includes(budget));assert.equal(Boolean(r.body.bookingUrl),['4000_6999','7000_9999','10000_plus'].includes(budget));if(r.body.bookingUrl){const p=new URL(r.body.bookingUrl).searchParams;assert.equal(p.get('a6'),'Canada');assert.equal(p.get('email'),b.email);assert.equal(p.get('a2'),'https://example.com/');}}assert.ok(events.every(e=>e.prospect_email_html&&e.owner_email_html&&!('forecast_range'in e)));assert.equal((await submit({...b,budget:'invalid'})).code,400);assert.equal((await submit({...b,budget:'4000_6999',website:'javascript:alert(1)'})).code,400);const r=await submit({type:'resource',name:'Buyer',email:'buyer@example.com',website:'example.com',region:'gcc',marketingConsent:false});assert.equal(r.body.resourceUrl,'https://www.bpohive.com/guides/gcc');assert.equal(events.at(-1).marketing_consent,false);global.fetch=async()=>({ok:false});assert.equal((await submit({type:'contact',name:'Buyer',email:'buyer@example.com',message:'Inquiry'})).code,502);}
 finally{global.fetch=old;if(hook===undefined)delete process.env.ZAPIER_WEBHOOK_URL;else process.env.ZAPIER_WEBHOOK_URL=hook;}
});
