const fs=require('node:fs'),path=require('node:path'),cheerio=require('cheerio');
const {marked}=require('marked');
const {regions,services,industries}=require('./growth-content.cjs');
const policy=require('../lib/campaign-policy.cjs');
const ROOT=path.resolve(__dirname,'..'),DATE='2026-10-04',ORIGIN='https://www.bpohive.com';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const codes=['US','CA','AE','SA','QA','KW','BH','OM'];
const area=xs=>xs.map(identifier=>({'@type':'Country',identifier,name:({US:'United States',CA:'Canada',AE:'United Arab Emirates',SA:'Saudi Arabia',QA:'Qatar',KW:'Kuwait',BH:'Bahrain',OM:'Oman'})[identifier]}));
const org={'@type':'Organization','@id':ORIGIN+'/#organization',name:'BPO Hive',url:ORIGIN,email:'info@bpohive.com',telephone:'+15026773800',areaServed:area(codes),contactPoint:[{'@type':'ContactPoint',contactType:'sales',telephone:'+15026773800',areaServed:['US','CA']},{'@type':'ContactPoint',contactType:'sales',telephone:'+971563755110',areaServed:['AE','SA','QA','KW','BH','OM']}]};
const author={'@type':'Person','@id':ORIGIN+'/about#amr-abdelrazzak',name:'Amr Abdelrazzak',jobTitle:'Founder and CEO',url:ORIGIN+'/about',worksFor:{'@id':ORIGIN+'/#organization'}};
const ld=data=>`<script type="application/ld+json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script>`;
const byline=`<p class="byline">By <a href="/about#amr-abdelrazzak">Amr Abdelrazzak</a>, Founder &amp; CEO · Last updated <time datetime="${DATE}">4 October 2026</time></p>`;
const cta='<p><a class="growth-button" href="/outbound-assessment">Book a strategy call</a></p><p class="growth-caption">Managed campaigns start at $4,000/month. No obligation to proceed.</p>';
function faqs(items){return '<section aria-label="Frequently asked questions"><h2>Frequently asked questions</h2>'+items.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')+'</section>';}
function page(out,slug,title,h1,answer,body,faq=[],service=false,territories=codes){
 const $=cheerio.load(fs.readFileSync(path.join(ROOT,'pricing.html'),'utf8'));
 $('title').text(title+' | BPO Hive');$('meta[name="description"],meta[property="og:description"],meta[name="twitter:description"]').attr('content',answer);
 $('meta[property="og:title"],meta[name="twitter:title"]').attr('content',title);$('link[rel="canonical"],meta[property="og:url"]').each((i,e)=>$(e).attr(e.tagName==='link'?'href':'content',ORIGIN+'/'+slug));
 $('script[type="application/ld+json"]').remove();
 $('main').html(`<article class="growth"><p class="eyebrow">BPO Hive · USA, Canada &amp; GCC</p><h1>${esc(h1)}</h1><p class="answer">${esc(answer)}</p>${byline}${cta}<div class="content">${body}${faqs(faq)}${cta}</div></article>`);
 const graph=[org,author,{'@type':'WebPage','@id':ORIGIN+'/'+slug,url:ORIGIN+'/'+slug,name:h1,dateModified:DATE,author:{'@id':author['@id']}}];
 if(service)graph.push({'@type':'Service',name:h1,provider:{'@id':org['@id']},areaServed:area(territories),url:ORIGIN+'/'+slug,description:answer});
 if(faq.length)graph.push({'@type':'FAQPage',mainEntity:faq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
 $('head').append(ld({'@context':'https://schema.org','@graph':graph}));
 // Root-relative paths allow the same design wrapper at /vs/* and /services/*.
 $('a[href],img[src],script[src],link[href]').each((i,e)=>{for(const attr of ['href','src']){let v=$(e).attr(attr);if(v&&!/^(?:[a-z]+:|\/|#)/i.test(v))$(e).attr(attr,'/'+v);}});
 const dest=path.join(out,slug+'.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,$.html());
}
const processCopy=`
## The ACES campaign process

**Analyze.** Begin with your offer, ideal customer profile, territory and existing sales evidence. Identify the accounts your business can serve, the roles that influence a purchase and the reasons those people might consider a conversation. Review current customers, open opportunities and suppression records so the campaign does not create avoidable overlap. The output is an agreed audience and a practical description of a useful lead.

**Contrive.** Turn that analysis into a campaign plan. Define the message, channels, qualification questions and sales handoff. Agree what agents can say, which claims need evidence and which questions should go to your team. A clear plan also records the contact approach, local scheduling constraints and the response to opt-outs. Scope should be understandable before execution begins.

**Execute.** Carry out the approved research and outreach, review responses and coordinate agreed next steps. A touchpoint means one outreach action; it is not a unique prospect, meeting or sale. Phone, email and LinkedIn can support one coherent conversation when appropriate to the audience and applicable rules. The campaign should preserve context across channels instead of sending unrelated messages to the same account.

**Scale.** Review what happened before adding volume. Compare relevant conversations, accepted appointments and sales feedback within each audience. A weak segment may need a better offer, different roles or a pause rather than more activity. Expand only when the evidence and your sales capacity support it. The purpose of the process is controlled learning and a useful pipeline, not a guarantee that every market will respond.

## Scope, pricing and responsibilities

Managed campaigns start at **$4,000 per month**. The starting scope is agreed around one practical campaign objective and includes market and customer-profile analysis, campaign preparation, coordinated outreach, qualification, calendar handoff and reporting as specified in the proposal. Higher-volume Growth and Enterprise programs are custom quoted. The written scope determines channel allocation, capacity, languages, data work and any third-party costs. A service page is not a promise that every possible activity is included at the minimum price.

${policy.portal}

${policy.insights}

${policy.exceptionCopy}

Before launch, your team supplies accurate product information, approved claims, target exclusions and the people who will take meetings. You retain responsibility for your offer, detailed discovery, proposals and closing. We agree the working relationship so a prospect does not wait for a response after showing interest. If your team cannot handle the intended meeting capacity, adjust the campaign before increasing outreach.

## What to measure

Track outreach activity, reached prospects, meaningful conversations, qualified interest, booked appointments and held meetings separately. A qualified meeting meets the agreed fit criteria and has an accepted next step; it is not automatically a qualified sales opportunity. Your sales team determines whether discovery establishes a real opportunity and records the reason. This distinction makes reports useful and prevents optimistic stage labels from hiding weak fit.

Review rejected meetings, cancellations and no-shows alongside positive outcomes. Look for patterns in account type, role, message and handoff quality. Use your own conversion history when estimating economics; do not substitute an unsourced industry show rate or close rate. BPO Hive reports 21,200+ appointments and $25M+ in client revenue across its work. These are company-reported cumulative figures, not forecasts for a particular engagement.
`;
const coreFaq=[['What is the minimum budget?','Managed campaigns start at $4,000 per month. Higher-volume or more complex programs are quoted after the market, language and delivery scope are agreed.'],['Are meetings or revenue guaranteed?','No. Activity scope and process commitments are defined in the agreement. Responses, attendance, opportunities and revenue depend on the market, offer and sales execution.'],['What does our sales team need to do?','Provide an accurate offer, approve targeting and messaging, attend agreed meetings and give timely feedback. Your team handles detailed discovery, proposals and closing.']];
function generate(out){
 for(const r of regions){
 const answer=`BPO Hive plans managed B2B appointment-setting campaigns for ${r.name}, combining account research, outreach, qualification and calendar handoff. Campaigns start at $4,000 per month, with language, local hours and contact requirements agreed before launch.`;
 const body=marked.parse(`## Why ${r.city} outreach needs a specific plan\n\n${r.pain}\n\n## Local buyers and procurement\n\n${r.local}\n\n## Calling hours and languages\n\n${r.hours}\n\nLanguage coverage: **${r.language}**. The signed scope establishes actual staffing and availability; discuss requirements before scheduling a campaign. Your closer’s calendar should show the prospect’s local time and leave enough capacity for preparation and follow-up.\n\n## Contact permissions and data handling\n\n${r.law}\n\n[Read the official guidance](${r.source}). This is a planning checklist, not campaign-specific legal advice or a compliance certification. Ask who owns the contact records, how opt-outs are enforced and how data is retained or deleted at the end of the engagement.\n\n## A local campaign example\n\n${r.case}\n\n${processCopy}\n\n## Choose the right next step\n\nIf your offer and monthly budget are ready, book a strategy call and tell us which buyers you want to reach. If you are still evaluating the economics, use the [ROI calculator](/roi-calculator) with your own assumptions and download the [regional planning guide](/resources?region=${r.guide}).\n\nExplore [appointment setting](/services/appointment-setting), [cold calling](/services/cold-calling) and [outsourced sales development](/services/sales-development). Compare [pricing](/pricing) before choosing a scope. ${r.slug==='gcc'?'Read the dedicated [UAE page](/appointment-setting-uae-dubai) and [Saudi Arabia page](/appointment-setting-saudi-arabia).':''}`);
 page(out,r.slug,r.title,r.h1,answer,body,[...coreFaq,[`Which languages are covered in ${r.name}?`,r.language+'. Confirm the required mix and staffing before launch.'],['How are calling hours planned?',r.hours]],true,r.codes);
 }
 for(const s of services){const [slug,h1,answer,intro,delivery,example,i1,i2]=s;
 const body=marked.parse(`## What this service should accomplish\n\n${intro}\n\n## Delivery and qualification\n\n${delivery}\n\n## An illustrative campaign\n\n${example}\n\n${processCopy}\n\n## Discuss your audience\n\nStart with the business problem, the type of organization you can serve and the person who should attend a useful meeting. Bring your current sales capacity and any evidence from previous outreach. We can then decide whether a managed campaign has a sensible starting point. If you are still defining those inputs, use the assessment to organize them before choosing a time.\n\nSee how this applies to [${i1.replaceAll('-',' ')}](/industries/${i1}) and [${i2.replaceAll('-',' ')}](/industries/${i2}). Review [Canada coverage](/appointment-setting-canada), [USA coverage](/appointment-setting-usa), [GCC coverage](/gcc) and [pricing](/pricing).`);
 page(out,'services/'+slug,h1+' · USA, Canada & GCC',h1,answer,body,[...coreFaq,['Which markets can we target?','Campaigns can be scoped for the USA, Canada and GCC. Confirm countries, language, buyer-local hours and applicable contact rules before launch.']],true);
 }
 for(const x of industries){const [slug,label,business,buyers,criteria,intro,delivery,example]=x;
 const answer=`BPO Hive helps ${business} build a more focused outbound process. Campaigns connect research, outreach and qualification for ${buyers}, with managed scope starting at $4,000 per month.`;
 const body=marked.parse(`## Find the right ${label.toLowerCase()} audience\n\n${intro}\n\n## Qualification that fits your sales process\n\n${delivery}\n\nAgree the qualification checklist around **${criteria}**. An agent should know which details are essential for a useful first meeting and which belong in specialist discovery. Record unknowns honestly; do not fill missing fields with assumptions simply to pass a lead to sales.\n\n## An illustrative ${label.toLowerCase()} campaign\n\n${example}\n\n${processCopy}\n\n## Markets and next steps\n\nWe scope campaigns for the [USA](/appointment-setting-usa), [Canada](/appointment-setting-canada) and [GCC](/gcc). The same commercial service may need a different audience definition, language plan and contact approach in each country. Start with the market your team can serve reliably, then expand after reviewing evidence.\n\nExplore [appointment setting](/services/appointment-setting), [lead research](/services/lead-research) and [sales development](/services/sales-development). Use the [cost guide](/appointment-setting-cost) to compare a managed engagement with your current approach.`);
 page(out,'industries/'+slug,label+' Lead Generation · USA, Canada & GCC',label+' lead generation and appointment setting',answer,body,[...coreFaq,[`How do you qualify ${label.toLowerCase()} leads?`,`We agree the criteria before launch, including ${criteria}. The sales handoff records fit, interest and an agreed next step; it is not a promise of a completed sale.`]],true);
 }
 const cost=marked.parse(`## Start with the scope, not a cost-per-lead promise\n\nBPO Hive managed campaigns start at **$4,000 per month**. Growth and Enterprise scopes are custom quoted. The scope should state audience, channels, research, languages, reporting, meeting qualification and any third-party costs. A touchpoint is an outreach action, not a unique prospect or a booked meeting.\n\n## A worked planning example\n\nIf you spend $4,000 and book 10 calls, your cost per booked call is $400. If 7 are held, cost per held call is about $571. If 2 become accepted opportunities, cost per opportunity is $2,000. These numbers are hypothetical arithmetic, not BPO Hive results or a forecast. Replace every assumption with your own evidence.\n\n## Compare like with like\n\nInclude people, research, software, management time and ramp-up when evaluating an internal team. Check whether an agency quote is per calendar month or per four weeks; there are 13 four-week periods in 52 weeks. Check commitment, cancellation, setup fees and what happens when meetings do not meet agreed criteria. Lower price per appointment can conceal weaker fit or substantial client work.\n\n## Break-even inputs\n\nUse gross contribution per won deal, not only headline revenue. Break-even wins equal campaign cost divided by contribution per win. Then assess how many held meetings and opportunities your actual sales process needs to produce those wins. A short campaign may not mature into closed revenue within the same month.\n\nUse the [ROI calculator](/roi-calculator), read [pricing](/pricing), or compare [in-house SDRs](/vs/in-house-sdr).`);
 page(out,'appointment-setting-cost','Appointment Setting Cost & ROI','What does appointment setting cost?','Managed BPO Hive campaigns start at $4,000 per month. Compare cost per booked call, held meeting and accepted opportunity separately, using your own sales assumptions.',cost,coreFaq);
 for(const competitor of ['in-house-sdr','belkins','salesroads']){
 const label=competitor==='in-house-sdr'?'an in-house SDR team':competitor==='belkins'?'Belkins':'SalesRoads';
 let text=competitor==='in-house-sdr'?`## Control, capacity and management\n\nAn internal SDR team can develop deep product knowledge and direct day-to-day alignment with sales. It also requires recruiting, coaching, data, software and management. Managed outsourcing can provide a defined operating process and external capacity, but still needs a client owner and a clear offer. Neither model fixes an unvalidated proposition automatically.\n\n## Compare total cost\n\nBuild your own internal budget: base compensation, variable pay, employer costs, recruiting, management time, software and research. We do not publish an invented universal SDR salary. BPO Hive starts at $4,000 per month for an agreed managed campaign; that is not a claim that a full-time dedicated SDR is included at the minimum.\n\n## Which model fits?\n\nConsider an internal team when direct control, product complexity and long-term organizational knowledge justify the investment. Consider a managed campaign when you have a clear offer, sales follow-up capacity and a defined audience to test. A hybrid can retain discovery and closing internally while outsourcing research and initial outreach.`:
 `## Compare scope before comparing price\n\nThis is a BPO Hive-authored buyer guide, not an independent ranking. BPO Hive supports campaigns for USA, Canada and GCC markets with a starting managed budget of $4,000 per month. The written proposal defines capacity, language, channels and deliverables.\n\n${competitor==='belkins'?'Belkins publishes a scope covering sales analysis, audience research, copy, scheduling and campaign optimization on its pricing page. Obtain a current quote for the specific program you need; this comparison does not invent a universal Belkins price.':'SalesRoads lists a one-dedicated-SDR program at $11,950 per four-week engagement and two SDRs at $16,750 on its pricing page checked 26 September 2026. These are different staffing scopes and billing periods from a BPO Hive starts-at monthly campaign; comparing the numbers alone would be misleading.'}\n\n[Check ${label}’ current pricing and scope](${competitor==='belkins'?'https://belkins.io/pricing':'https://salesroads.com/pricing/'}). Prices and packages can change.\n\n## Questions to ask both providers\n\nAsk who performs research, how the contact approach is reviewed, which languages and working hours are staffed, and what counts as an accepted meeting. Request the same written definition of scope from both providers. Confirm account ownership, reporting access, third-party costs, minimum commitment and cancellation terms. Ask for evidence relevant to your industry without assuming that one client’s outcome predicts yours.\n\n## Decide on fit\n\nUse a scorecard for audience experience, operational transparency, meeting quality, client responsibilities and total cost. A provider with a larger or differently staffed program may be a better fit for your needs. BPO Hive is an option when its market coverage and agreed campaign scope fit your budget and sales process; no claim of universal superiority is made.`;
 text+='\n\nReview [BPO Hive pricing](/pricing), [appointment-setting costs](/appointment-setting-cost) and [our campaign process](/services/appointment-setting).';
 page(out,'vs/'+competitor,competitor==='in-house-sdr'?'Outsourced SDR vs In-House':'BPO Hive vs '+label,competitor==='in-house-sdr'?'Outsourced SDR or an in-house team?':'Comparing BPO Hive and '+label,'Compare the audience, staffing, qualification standard, billing period and total operating cost before choosing an outbound model. BPO Hive managed campaigns start at $4,000 per month.',marked.parse(text),coreFaq);
 }
}
module.exports={generate,page,org,author,ld,byline,DATE,ORIGIN,area,faqs,coreFaq};
